# Generated by Django 6.0.8 on 2026-08-12 15:27

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description for the card')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', validators=[website.models.validate_image_size, website.models.validate_image_extension])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destination', models.CharField(blank=True, help_text='e.g. Tamil Nadu', max_length=255, null=True)),
                ('tourist_place', models.CharField(blank=True, help_text='e.g. Marina Beach', max_length=255, null=True)),
                ('pickup', models.CharField(max_length=255)),
                ('drop', models.CharField(default='', max_length=255)),
                ('travel_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Enquiry',
                'verbose_name_plural': 'Travel Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='OutstationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text='e.g. Coimbatore to Chennai', max_length=100)),
                ('destination_name', models.CharField(help_text='e.g. Chennai', max_length=100)),
                ('image', models.ImageField(upload_to='outstation_routes/', validators=[website.models.validate_image_size, website.models.validate_image_extension])),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Popular, Trending', max_length=50, null=True)),
                ('short_description', models.TextField(help_text='SEO friendly short description.')),
                ('travel_time', models.CharField(help_text='e.g. 8 Hours 30 Mins', max_length=50)),
                ('distance', models.CharField(help_text='e.g. 510 Kms', max_length=50)),
                ('vehicle_types', models.CharField(help_text='e.g. Sedan, SUV, Innova Crysta, TT', max_length=255)),
                ('starting_price', models.CharField(help_text='e.g. 4999', max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Outstation Route',
                'verbose_name_plural': 'Outstation Routes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.CharField(help_text='e.g. SUV, Sedan, Mini Bus', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='e.g. Etios / Dzire', max_length=100)),
                ('price', models.CharField(blank=True, help_text='e.g. ₹1800 / Day', max_length=50)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Best Seller', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='vehicles/', validators=[website.models.validate_image_size, website.models.validate_image_extension])),
                ('short_description', models.TextField(blank=True, help_text='Maximum 2 lines')),
                ('passengers', models.PositiveIntegerField(default=4, help_text='Passenger Capacity')),
                ('luggage', models.CharField(blank=True, help_text='e.g. 3 Bags', max_length=50)),
                ('ac_type', models.CharField(default='AC', help_text='e.g. AC / Non AC', max_length=50)),
                ('transmission', models.CharField(default='Manual', help_text='e.g. Manual / Automatic', max_length=50)),
                ('fuel_type', models.CharField(default='Diesel', help_text='e.g. Diesel / Petrol / EV', max_length=50)),
                ('has_driver', models.BooleanField(default=True, verbose_name='Professional Driver')),
                ('has_music', models.BooleanField(default=True, verbose_name='Music System')),
                ('has_charging', models.BooleanField(default=True, verbose_name='Charging Port')),
                ('has_pushback', models.BooleanField(default=False, verbose_name='Push Back Seat')),
                ('feature_tags', models.CharField(blank=True, help_text='Comma separated (e.g. GPS, Fast Charging, Luxury Seats)', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/', validators=[website.models.validate_image_size, website.models.validate_image_extension])),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.vehicle')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
