# Generated by Django 6.0.8 on 2026-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='e.g. Coimbatore, Madurai, Chennai, Bangalore, Kochi', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('primary_keywords', models.TextField(blank=True, help_text='Priority A keywords (comma or newline separated)')),
                ('route_keywords', models.TextField(blank=True, help_text='Priority C route keywords (comma or newline separated)')),
                ('seo_content', models.TextField(blank=True, help_text='Custom HTML/Text content block for city page')),
                ('image_alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City SEO Content',
                'verbose_name_plural': 'City SEO Content',
                'ordering': ['city_name'],
            },
        ),
    ]
