# Generated by Django 6.0.8 on 2026-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cityseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityseo',
            name='airport_keywords',
            field=models.TextField(blank=True, help_text='Airport keywords (comma or newline separated)'),
        ),
        migrations.AddField(
            model_name='cityseo',
            name='corporate_keywords',
            field=models.TextField(blank=True, help_text='Corporate & B2B keywords (comma or newline separated)'),
        ),
        migrations.AddField(
            model_name='cityseo',
            name='segment_keywords',
            field=models.TextField(blank=True, help_text='Tour Segment keywords like School/College/Family/Pilgrimage (comma or newline separated)'),
        ),
        migrations.AddField(
            model_name='cityseo',
            name='wedding_event_keywords',
            field=models.TextField(blank=True, help_text='Wedding & Event keywords (comma or newline separated)'),
        ),
    ]
