# Generated by Django 6.0.8 on 2026-08-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_cityseo_airport_keywords_cityseo_corporate_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='left_features',
            field=models.TextField(blank=True, default='Luxury Vehicles\nWell Maintained\nAC & Comfort\nLuggage Space\nDriver Included', help_text='Enter left feature card items (one per line)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='right_specifications',
            field=models.TextField(blank=True, default='12–17 Seater\nPremium Interiors\nAC & Comfortable Seats\nLuggage Space\nDriver & Fuel Included', help_text='Enter right specifications list items (one per line)'),
        ),
        migrations.CreateModel(
            name='Vehicle360Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_360/')),
                ('frame_number', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames_360', to='website.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle 360° Frame',
                'verbose_name_plural': 'Vehicle 360° Frames',
                'ordering': ['display_order', 'frame_number', 'id'],
            },
        ),
    ]
