# Generated by Django 6.0.8 on 2026-08-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_vehicle_left_features_vehicle_right_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ai_360_error',
            field=models.TextField(blank=True, help_text='Error logs if AI generation fails'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ai_360_status',
            field=models.CharField(choices=[('pending', 'Pending Generation'), ('processing', 'AI 360° Processing'), ('completed', 'AI 360° Ready'), ('failed', 'Generation Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ai_subject_type',
            field=models.CharField(blank=True, help_text='Detected subject: e.g. Tempo Traveller, SUV, Bus', max_length=50),
        ),
        migrations.CreateModel(
            name='VehicleAI360Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_ai_360/')),
                ('angle_degree', models.IntegerField(default=0, help_text='Rotation angle (0 to 360)')),
                ('frame_number', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_360_frames', to='website.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle AI 360° Frame',
                'verbose_name_plural': 'Vehicle AI 360° Frames',
                'ordering': ['display_order', 'angle_degree', 'frame_number', 'id'],
            },
        ),
    ]
