# Generated by Django 6.0.8 on 2026-08-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_vehicle_ai_360_error_vehicle_ai_360_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='ai_360_error',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='ai_360_status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='ai_subject_type',
        ),
    ]
