# Generated by Django 6.0.8 on 2026-08-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_vehicle_ai_360_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleai360frame',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle360Frame',
        ),
        migrations.DeleteModel(
            name='VehicleAI360Frame',
        ),
    ]
