# Generated by Django 6.0.8 on 2026-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_vehicleai360frame_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='above_400_applicable',
            field=models.BooleanField(default=True, verbose_name='Above 400 KM Applicable'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='day_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Day Rent Up To 400 KM (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_pay_above_400',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driver Pay Above 400 KM (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='flat_per_km_above_400',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat Per KM Above 400 KM (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='karnataka_permit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Karnataka Permit Cost (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kerala_permit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kerala Permit Cost (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='per_km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per KM Rate Up To 400 KM (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
