# Generated by Django 6.0.8 on 2026-08-20 12:21

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_vehicle_above_400_applicable_vehicle_day_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_video',
            field=models.FileField(blank=True, help_text='Upload optional vehicle video (.mp4 or .webm)', null=True, upload_to='vehicles/videos/', validators=[website.models.validate_video_extension], verbose_name='Vehicle Video'),
        ),
    ]
