# Generated by Django 6.0.8 on 2026-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_vehicle_vehicle_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Luxury Car', 'Luxury Car'), ('Tempo Traveller', 'Tempo Traveller'), ('Mini Bus', 'Mini Bus'), ('Tourist Bus', 'Tourist Bus'), ('Other', 'Other')], max_length=50, verbose_name='Vehicle Type')),
                ('vehicle_count', models.CharField(default='1', max_length=50, verbose_name='Number of Vehicles')),
                ('service_type', models.CharField(choices=[('Local Travel', 'Local Travel'), ('Airport Transfer', 'Airport Transfer'), ('Outstation Travel', 'Outstation Travel'), ('Tour Packages', 'Tour Packages'), ('Corporate Travel', 'Corporate Travel'), ('Wedding / Event Travel', 'Wedding / Event Travel'), ('All Services', 'All Services')], max_length=100, verbose_name='Preferred Service')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message / Additional Info')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fleet Partner Inquiry',
                'verbose_name_plural': 'Fleet Partner Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
