# Generated by Django 6.0.8 on 2026-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_fleetpartnerinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetpartnerinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fleet Partner Application', 'verbose_name_plural': 'Fleet Partner Applications'},
        ),
        migrations.RenameField(
            model_name='fleetpartnerinquiry',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='fleetpartnerinquiry',
            name='state',
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Local Travel', 'Local Travel'), ('Airport Transfer', 'Airport Transfer'), ('Outstation Travel', 'Outstation Travel'), ('Tour Packages', 'Tour Packages'), ('Corporate Travel', 'Corporate Travel'), ('All Services', 'All Services')], max_length=100, null=True, verbose_name='Service Preference'),
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='vehicle_count',
            field=models.CharField(max_length=50, verbose_name='Number of Vehicles'),
        ),
        migrations.AlterField(
            model_name='fleetpartnerinquiry',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Luxury Car', 'Luxury Car'), ('Tempo Traveller', 'Tempo Traveller'), ('Mini Bus', 'Mini Bus'), ('Tourist Bus', 'Tourist Bus')], max_length=50, verbose_name='Vehicle Type'),
        ),
    ]
