# Generated by Django 6.0.8 on 2026-08-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_fleetpartnerinquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Tempo Traveller', 'Tempo Traveller'), ('Luxury Bus', 'Luxury Bus'), ('Other', 'Other')], max_length=50, verbose_name='Vehicle Type')),
                ('vehicle_count', models.CharField(max_length=50, verbose_name='Number of Vehicles')),
                ('vehicle_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Model / Details')),
                ('preferred_service', models.CharField(choices=[('Local Cab Service', 'Local Cab Service'), ('Outstation Travel', 'Outstation Travel'), ('Airport Transfer', 'Airport Transfer'), ('Corporate Travel', 'Corporate Travel'), ('Tourist Packages', 'Tourist Packages'), ('All Services', 'All Services')], max_length=100, verbose_name='Preferred Service')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Enquiry',
                'verbose_name_plural': 'Partner Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
