# Generated by Django 6.0.8 on 2026-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_partnerenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='City Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OneWayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('pickup_time', models.CharField(max_length=50, verbose_name='Pick Up Time')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='Pickup City')),
                ('drop_city', models.CharField(max_length=100, verbose_name='Drop Off City')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
            ],
            options={
                'verbose_name': 'One Way Booking',
                'verbose_name_plural': 'One Way Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneWayFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100, verbose_name='From City')),
                ('to_city', models.CharField(max_length=100, verbose_name='To City')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Fare (₹)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'One Way Fare',
                'verbose_name_plural': 'One Way Fares',
                'ordering': ['from_city', 'to_city'],
            },
        ),
    ]
