# Generated by Django 6.0.8 on 2026-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_city_onewaybooking_onewayfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='Pickup City')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('pickup_time', models.CharField(max_length=50, verbose_name='Pick Up Time')),
                ('dropoff_date', models.DateField(verbose_name='Drop Off Date')),
                ('dropoff_time', models.CharField(max_length=50, verbose_name='Drop Off Time')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
            ],
            options={
                'verbose_name': 'Round Trip Booking',
                'verbose_name_plural': 'Round Trip Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundTripFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100, verbose_name='From City')),
                ('place', models.CharField(max_length=150, verbose_name='Place / Route')),
                ('distance_km', models.CharField(max_length=50, verbose_name='Km')),
                ('trip_duration', models.CharField(max_length=50, verbose_name='Trip Duration')),
                ('sedan_fare', models.CharField(max_length=50, verbose_name='Sedan Fare')),
                ('mini_fare', models.CharField(max_length=50, verbose_name='Mini / SUV Fare')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Round Trip Fare',
                'verbose_name_plural': 'Round Trip Fares',
                'ordering': ['from_city', 'display_order'],
            },
        ),
    ]
