# Generated by Django 6.0.8 on 2026-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_roundtripbooking_roundtripfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRentalFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('vehicle_type', models.CharField(choices=[('Sedan / Hatchback', 'Sedan / Hatchback'), ('SUV / MUV', 'SUV / MUV'), ('Tempo Traveller', 'Tempo Traveller'), ('Luxury Bus', 'Luxury Bus')], max_length=100, verbose_name='Vehicle Type')),
                ('hours', models.IntegerField(default=1, verbose_name='Hours')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Fare')),
                ('free_km', models.IntegerField(default=10, verbose_name='Free KM')),
                ('extra_km_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Extra KM Fare')),
                ('extra_minute_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Extra Minute Fare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hourly Rental Fare',
                'verbose_name_plural': 'Hourly Rental Fares',
                'ordering': ['city', 'vehicle_type', 'hours'],
            },
        ),
    ]
