# Generated by Django 6.0.8 on 2026-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_hourlyrentalfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='Pickup City')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Bulk Booking',
                'verbose_name_plural': 'Bulk Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
