# Generated by Django 6.0.8 on 2026-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_bulkbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtripbooking',
            name='destination',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination / Route'),
        ),
        migrations.AddField(
            model_name='roundtripbooking',
            name='passengers',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passengers'),
        ),
        migrations.AddField(
            model_name='roundtripbooking',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='roundtripbooking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, verbose_name='Status'),
        ),
    ]
