# Generated by Django 6.0.8 on 2026-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_roundtripbooking_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='Pickup City')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('pickup_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pickup Time')),
                ('vehicle_type', models.CharField(default='Sedan / Hatchback', max_length=100, verbose_name='Vehicle Type')),
                ('hours', models.CharField(default='4 Hours', max_length=50, verbose_name='Number of Hours')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments / Special Requirements')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, verbose_name='Booking Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Hourly Rental Booking',
                'verbose_name_plural': 'Hourly Rental Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
