# Generated by Django 6.0.8 on 2026-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_hourlyrentalbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
