# Generated by Django 6.0.8 on 2026-08-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
